export interface BankBranch {
  id: string;
  bankId: string;
  bankName: string;
  name: string;
  address: string;
  latitude: number | null;
  longitude: number | null;
  foreignSupport: boolean;
  distanceKm: number | null;
  successfulExperiences: number;
  verifiedAt: string;
  sourceUrl: string;
}

import branchAsset from "../data/bank-branches.json";

type BranchAsset = {
  id: string;
  bank_id: string;
  bank_name: string;
  name: string;
  address: string;
  latitude: number | null;
  longitude: number | null;
  foreign_support: boolean;
  verified_at: string;
  source_url: string;
};

const DAEJEON_CITY_HALL = { latitude: 36.3504, longitude: 127.3845 };

function distanceFromDaejeonCityHall(latitude: number | null, longitude: number | null): number | null {
  if (latitude === null || longitude === null) return null;

  const earthRadiusKm = 6371;
  const toRadians = (value: number) => (value * Math.PI) / 180;
  const latitudeDelta = toRadians(latitude - DAEJEON_CITY_HALL.latitude);
  const longitudeDelta = toRadians(longitude - DAEJEON_CITY_HALL.longitude);
  const haversine =
    Math.sin(latitudeDelta / 2) ** 2 +
    Math.cos(toRadians(DAEJEON_CITY_HALL.latitude)) * Math.cos(toRadians(latitude)) * Math.sin(longitudeDelta / 2) ** 2;

  return Math.round(earthRadiusKm * 2 * Math.atan2(Math.sqrt(haversine), Math.sqrt(1 - haversine)) * 10) / 10;
}

/** FN-3101~FN-3105. Generated by the standalone crawler and bundled as a static asset. */
export const BANK_BRANCHES: BankBranch[] = branchAsset.branches.map((branch: BranchAsset) => ({
  id: branch.id,
  bankId: branch.bank_id,
  bankName: branch.bank_name,
  name: branch.name,
  address: branch.address,
  latitude: branch.latitude,
  longitude: branch.longitude,
  foreignSupport: branch.foreign_support,
  distanceKm: distanceFromDaejeonCityHall(branch.latitude, branch.longitude),
  successfulExperiences: 0,
  verifiedAt: branch.verified_at,
  sourceUrl: branch.source_url,
}));
