export interface BankBranch {
  id: string;
  bankId: string;
  bankName: string;
  name: string;
  address: string;
  latitude: number | null;
  longitude: number | null;
  foreignSupport: boolean;
  distanceKm: number | null;
  successfulExperiences: number;
  verifiedAt: string;
  sourceUrl: string;
}

import branchAsset from "../data/bank-branches.json";

type BranchAsset = {
  id: string;
  bank_id: string;
  bank_name: string;
  name: string;
  address: string;
  latitude: number | null;
  longitude: number | null;
  foreign_support: boolean;
  verified_at: string;
  source_url: string;
};

type BranchCatalog = {
  city?: string;
  branches: BranchAsset[];
};

const DAEJEON_CITY_HALL = { latitude: 36.3504, longitude: 127.3845 };

function distanceFromDaejeonCityHall(latitude: number | null, longitude: number | null): number | null {
  if (latitude === null || longitude === null) return null;

  const earthRadiusKm = 6371;
  const toRadians = (value: number) => (value * Math.PI) / 180;
  const latitudeDelta = toRadians(latitude - DAEJEON_CITY_HALL.latitude);
  const longitudeDelta = toRadians(longitude - DAEJEON_CITY_HALL.longitude);
  const haversine =
    Math.sin(latitudeDelta / 2) ** 2 +
    Math.cos(toRadians(DAEJEON_CITY_HALL.latitude)) * Math.cos(toRadians(latitude)) * Math.sin(longitudeDelta / 2) ** 2;

  return Math.round(earthRadiusKm * 2 * Math.atan2(Math.sqrt(haversine), Math.sqrt(1 - haversine)) * 10) / 10;
}

function isBranchCatalog(value: unknown): value is BranchCatalog {
  return !!value && typeof value === "object" && Array.isArray((value as { branches?: unknown }).branches);
}

async function fetchBranchCatalog(url: string): Promise<BranchCatalog> {
  const response = await fetch(url, {
    method: "GET",
    cache: "no-store",
    headers: { Accept: "application/json" },
  });

  if (!response.ok) {
    throw new Error(`Branch catalog request failed: ${response.status}`);
  }

  const payload: unknown = await response.json();

  if (!isBranchCatalog(payload)) {
    throw new Error("Branch catalog payload shape is invalid.");
  }

  return payload;
}

async function resolveBranchCatalog(): Promise<BranchCatalog> {
  const configuredUrl = (import.meta.env.VITE_BANK_BRANCHES_URL ?? "").trim();

  if (configuredUrl) {
    try {
      return await fetchBranchCatalog(configuredUrl);
    } catch (error) {
      console.warn("[branch-catalog] Remote source failed; falling back to local asset.", error);
    }
  }

  try {
    if (!isBranchCatalog(branchAsset)) {
      throw new Error("Local branch catalog payload shape is invalid.");
    }

    return branchAsset;
  } catch (error) {
    console.error("[branch-catalog] Local asset fallback failed.", error);

    return { city: "대전", branches: [] };
  }
}

function mapBranchCatalogToBankBranches(branches: BranchAsset[]): BankBranch[] {
  return branches.map((branch) => ({
    id: branch.id,
    bankId: branch.bank_id,
    bankName: branch.bank_name,
    name: branch.name,
    address: branch.address,
    latitude: branch.latitude,
    longitude: branch.longitude,
    foreignSupport: branch.foreign_support,
    distanceKm: distanceFromDaejeonCityHall(branch.latitude, branch.longitude),
    successfulExperiences: 0,
    verifiedAt: branch.verified_at,
    sourceUrl: branch.source_url,
  }));
}

/** FN-3101~FN-3105. Generated by the standalone crawler and bundled as a static asset. */
export const BANK_BRANCHES: BankBranch[] = mapBranchCatalogToBankBranches((await resolveBranchCatalog()).branches);
