import type { TaskNode } from "./types";

/**
 * FN-5101~FN-5104 업무 마스터 시드.
 * 리드타임·기한 값은 아직 공식 출처로 확인되지 않은 초안이므로 verifiedAt 을 null 로 둔다.
 * FN-5104 규칙에 따라 확인 시각이 없는 항목은 화면에서 경고 상태로 표시된다.
 */
export const TASK_MASTER: TaskNode[] = [
  {
    id: "T01",
    nameKey: "task.T01.name",
    descriptionKey: "task.T01.desc",
    appliesTo: ["BEFORE_ENTRY", "BEFORE_REGISTRATION", "CHANGING_STATUS", "REGISTERED"],
    prerequisites: [],
    leadTimeDays: 1,
    deadlineType: "RELATIVE",
    baseDateRef: "ENTRY_DATE",
    deadlineOffsetDays: 3,
    collectsExperience: false,
    sourceUrl: "https://www.hikorea.go.kr",
    verifiedAt: null,
  },
  {
    id: "T02",
    nameKey: "task.T02.name",
    descriptionKey: "task.T02.desc",
    appliesTo: ["BEFORE_ENTRY", "BEFORE_REGISTRATION", "CHANGING_STATUS"],
    prerequisites: [],
    leadTimeDays: 7,
    deadlineType: "RELATIVE",
    baseDateRef: "ENTRY_DATE",
    deadlineOffsetDays: 14,
    collectsExperience: false,
    sourceUrl: null,
    verifiedAt: null,
  },
  {
    id: "T03",
    nameKey: "task.T03.name",
    descriptionKey: "task.T03.desc",
    appliesTo: ["BEFORE_REGISTRATION", "CHANGING_STATUS"],
    prerequisites: ["T01", "T02"],
    leadTimeDays: 14,
    deadlineType: "RELATIVE",
    baseDateRef: "ENTRY_DATE",
    deadlineOffsetDays: 90,
    collectsExperience: false,
    sourceUrl: "https://www.hikorea.go.kr",
    verifiedAt: null,
  },
  {
    id: "T04",
    nameKey: "task.T04.name",
    descriptionKey: "task.T04.desc",
    appliesTo: ["BEFORE_REGISTRATION", "CHANGING_STATUS"],
    prerequisites: ["T03"],
    leadTimeDays: 21,
    deadlineType: "RELATIVE",
    baseDateRef: "REGISTRATION_APPLIED_DATE",
    deadlineOffsetDays: 30,
    collectsExperience: false,
    sourceUrl: "https://www.hikorea.go.kr",
    verifiedAt: null,
  },
  {
    id: "T05",
    nameKey: "task.T05.name",
    descriptionKey: "task.T05.desc",
    appliesTo: ["BEFORE_REGISTRATION", "CHANGING_STATUS", "REGISTERED"],
    prerequisites: ["T01"],
    leadTimeDays: 3,
    deadlineType: "NONE",
    collectsExperience: true,
    sourceUrl: null,
    verifiedAt: null,
  },
  {
    id: "T06",
    nameKey: "task.T06.name",
    descriptionKey: "task.T06.desc",
    appliesTo: ["BEFORE_REGISTRATION", "CHANGING_STATUS", "REGISTERED"],
    prerequisites: ["T04", "T05"],
    leadTimeDays: 2,
    deadlineType: "NONE",
    collectsExperience: false,
    sourceUrl: null,
    verifiedAt: null,
  },
  {
    id: "T07",
    nameKey: "task.T07.name",
    descriptionKey: "task.T07.desc",
    appliesTo: ["BEFORE_REGISTRATION", "CHANGING_STATUS", "REGISTERED"],
    prerequisites: ["T04"],
    leadTimeDays: 5,
    deadlineType: "NONE",
    collectsExperience: false,
    sourceUrl: null,
    verifiedAt: null,
  },
  {
    id: "T08",
    nameKey: "task.T08.name",
    descriptionKey: "task.T08.desc",
    appliesTo: ["BEFORE_ENTRY", "BEFORE_REGISTRATION", "CHANGING_STATUS", "REGISTERED"],
    prerequisites: [],
    leadTimeDays: 5,
    deadlineType: "NONE",
    collectsExperience: false,
    sourceUrl: null,
    verifiedAt: null,
  },
  {
    id: "T09",
    nameKey: "task.T09.name",
    descriptionKey: "task.T09.desc",
    appliesTo: ["CHANGING_STATUS"],
    prerequisites: ["T08"],
    leadTimeDays: 30,
    deadlineType: "NONE",
    collectsExperience: false,
    sourceUrl: "https://www.hikorea.go.kr",
    verifiedAt: null,
  },
  {
    id: "T10",
    nameKey: "task.T10.name",
    descriptionKey: "task.T10.desc",
    appliesTo: ["BEFORE_REGISTRATION", "CHANGING_STATUS", "REGISTERED"],
    prerequisites: ["T04"],
    leadTimeDays: 1,
    deadlineType: "NONE",
    collectsExperience: false,
    sourceUrl: "https://www.hikorea.go.kr",
    verifiedAt: null,
  },
  {
    id: "T11",
    nameKey: "task.T11.name",
    descriptionKey: "task.T11.desc",
    appliesTo: ["BEFORE_REGISTRATION", "CHANGING_STATUS", "REGISTERED"],
    prerequisites: ["T05"],
    leadTimeDays: 1,
    deadlineType: "NONE",
    collectsExperience: false,
    sourceUrl: null,
    verifiedAt: null,
  },
  {
    id: "T12",
    nameKey: "task.T12.name",
    descriptionKey: "task.T12.desc",
    appliesTo: ["REGISTERED"],
    prerequisites: [],
    leadTimeDays: 14,
    deadlineType: "RELATIVE",
    baseDateRef: "CARD_EXPIRY_DATE",
    deadlineOffsetDays: -60,
    collectsExperience: false,
    sourceUrl: "https://www.hikorea.go.kr",
    verifiedAt: null,
  },
];

/** FN-2129. 이미 한국 번호가 있는 사용자에게 유심 개통을 최우선으로 띄우지 않는다. */
export const PHONE_NUMBER_TASK_ID = "T01";
